using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NeodymiumDotNet.Io.Numpy
{
    internal static class UnicodeUtils
    {

        public static string FromOct(string oct)
            => char.ConvertFromUtf32(Convert.ToInt32(oct, 8));


        public static string FromHex(string hex)
            => char.ConvertFromUtf32(Convert.ToInt32(hex, 16));


        public static string FromAlias(string alias)
        {
            int getCodePoint(string x)
            {
                switch(x.ToUpper())
                {
                case "NULL":                                     return 0x0000;
                case "NUL":                                      return 0x0000;
                case "START OF HEADING":                         return 0x0001;
                case "SOH":                                      return 0x0001;
                case "START OF TEXT":                            return 0x0002;
                case "STX":                                      return 0x0002;
                case "END OF TEXT":                              return 0x0003;
                case "ETX":                                      return 0x0003;
                case "END OF TRANSMISSION":                      return 0x0004;
                case "EOT":                                      return 0x0004;
                case "ENQUIRY":                                  return 0x0005;
                case "ENQ":                                      return 0x0005;
                case "ACKNOWLEDGE":                              return 0x0006;
                case "ACK":                                      return 0x0006;
                case "ALERT":                                    return 0x0007;
                case "BEL":                                      return 0x0007;
                case "BACKSPACE":                                return 0x0008;
                case "BS":                                       return 0x0008;
                case "CHARACTER TABULATION":                     return 0x0009;
                case "HORIZONTAL TABULATION":                    return 0x0009;
                case "HT":                                       return 0x0009;
                case "TAB":                                      return 0x0009;
                case "LINE FEED":                                return 0x000A;
                case "NEW LINE":                                 return 0x000A;
                case "END OF LINE":                              return 0x000A;
                case "LF":                                       return 0x000A;
                case "NL":                                       return 0x000A;
                case "EOL":                                      return 0x000A;
                case "LINE TABULATION":                          return 0x000B;
                case "VERTICAL TABULATION":                      return 0x000B;
                case "VT":                                       return 0x000B;
                case "FORM FEED":                                return 0x000C;
                case "FF":                                       return 0x000C;
                case "CARRIAGE RETURN":                          return 0x000D;
                case "CR":                                       return 0x000D;
                case "SHIFT OUT":                                return 0x000E;
                case "LOCKING-SHIFT ONE":                        return 0x000E;
                case "SO":                                       return 0x000E;
                case "SHIFT IN":                                 return 0x000F;
                case "LOCKING-SHIFT ZERO":                       return 0x000F;
                case "SI":                                       return 0x000F;
                case "DATA LINK ESCAPE":                         return 0x0010;
                case "DLE":                                      return 0x0010;
                case "DEVICE CONTROL ONE":                       return 0x0011;
                case "DC1":                                      return 0x0011;
                case "DEVICE CONTROL TWO":                       return 0x0012;
                case "DC2":                                      return 0x0012;
                case "DEVICE CONTROL THREE":                     return 0x0013;
                case "DC3":                                      return 0x0013;
                case "DEVICE CONTROL FOUR":                      return 0x0014;
                case "DC4":                                      return 0x0014;
                case "NEGATIVE ACKNOWLEDGE":                     return 0x0015;
                case "NAK":                                      return 0x0015;
                case "SYNCHRONOUS IDLE":                         return 0x0016;
                case "SYN":                                      return 0x0016;
                case "END OF TRANSMISSION BLOCK":                return 0x0017;
                case "ETB":                                      return 0x0017;
                case "CANCEL":                                   return 0x0018;
                case "CAN":                                      return 0x0018;
                case "END OF MEDIUM":                            return 0x0019;
                case "EOM":                                      return 0x0019;
                case "SUBSTITUTE":                               return 0x001A;
                case "SUB":                                      return 0x001A;
                case "ESCAPE":                                   return 0x001B;
                case "ESC":                                      return 0x001B;
                case "INFORMATION SEPARATOR FOUR":               return 0x001C;
                case "FILE SEPARATOR":                           return 0x001C;
                case "FS":                                       return 0x001C;
                case "INFORMATION SEPARATOR THREE":              return 0x001D;
                case "GROUP SEPARATOR":                          return 0x001D;
                case "GS":                                       return 0x001D;
                case "INFORMATION SEPARATOR TWO":                return 0x001E;
                case "RECORD SEPARATOR":                         return 0x001E;
                case "RS":                                       return 0x001E;
                case "INFORMATION SEPARATOR ONE":                return 0x001F;
                case "UNIT SEPARATOR":                           return 0x001F;
                case "US":                                       return 0x001F;
                case "SP":                                       return 0x0020;
                case "DELETE":                                   return 0x007F;
                case "DEL":                                      return 0x007F;
                case "PADDING CHARACTER":                        return 0x0080;
                case "PAD":                                      return 0x0080;
                case "HIGH OCTET PRESET":                        return 0x0081;
                case "HOP":                                      return 0x0081;
                case "BREAK PERMITTED HERE":                     return 0x0082;
                case "BPH":                                      return 0x0082;
                case "NO BREAK HERE":                            return 0x0083;
                case "NBH":                                      return 0x0083;
                case "INDEX":                                    return 0x0084;
                case "IND":                                      return 0x0084;
                case "NEXT LINE":                                return 0x0085;
                case "NEL":                                      return 0x0085;
                case "START OF SELECTED AREA":                   return 0x0086;
                case "SSA":                                      return 0x0086;
                case "END OF SELECTED AREA":                     return 0x0087;
                case "ESA":                                      return 0x0087;
                case "CHARACTER TABULATION SET":                 return 0x0088;
                case "HORIZONTAL TABULATION SET":                return 0x0088;
                case "HTS":                                      return 0x0088;
                case "CHARACTER TABULATION WITH JUSTIFICATION":  return 0x0089;
                case "HORIZONTAL TABULATION WITH JUSTIFICATION": return 0x0089;
                case "HTJ":                                      return 0x0089;
                case "LINE TABULATION SET":                      return 0x008A;
                case "VERTICAL TABULATION SET":                  return 0x008A;
                case "VTS":                                      return 0x008A;
                case "PARTIAL LINE FORWARD":                     return 0x008B;
                case "PARTIAL LINE DOWN":                        return 0x008B;
                case "PLD":                                      return 0x008B;
                case "PARTIAL LINE BACKWARD":                    return 0x008C;
                case "PARTIAL LINE UP":                          return 0x008C;
                case "PLU":                                      return 0x008C;
                case "REVERSE LINE FEED":                        return 0x008D;
                case "REVERSE INDEX":                            return 0x008D;
                case "RI":                                       return 0x008D;
                case "SINGLE SHIFT TWO":                         return 0x008E;
                case "SINGLE-SHIFT-2":                           return 0x008E;
                case "SS2":                                      return 0x008E;
                case "SINGLE SHIFT THREE":                       return 0x008F;
                case "SINGLE-SHIFT-3":                           return 0x008F;
                case "SS3":                                      return 0x008F;
                case "DEVICE CONTROL STRING":                    return 0x0090;
                case "DCS":                                      return 0x0090;
                case "PRIVATE USE ONE":                          return 0x0091;
                case "PRIVATE USE-1":                            return 0x0091;
                case "PU1":                                      return 0x0091;
                case "PRIVATE USE TWO":                          return 0x0092;
                case "PRIVATE USE-2":                            return 0x0092;
                case "PU2":                                      return 0x0092;
                case "SET TRANSMIT STATE":                       return 0x0093;
                case "STS":                                      return 0x0093;
                case "CANCEL CHARACTER":                         return 0x0094;
                case "CCH":                                      return 0x0094;
                case "MESSAGE WAITING":                          return 0x0095;
                case "MW":                                       return 0x0095;
                case "START OF GUARDED AREA":                    return 0x0096;
                case "START OF PROTECTED AREA":                  return 0x0096;
                case "SPA":                                      return 0x0096;
                case "END OF GUARDED AREA":                      return 0x0097;
                case "END OF PROTECTED AREA":                    return 0x0097;
                case "EPA":                                      return 0x0097;
                case "START OF STRING":                          return 0x0098;
                case "SOS":                                      return 0x0098;
                case "SINGLE GRAPHIC CHARACTER INTRODUCER":      return 0x0099;
                case "SGC":                                      return 0x0099;
                case "SINGLE CHARACTER INTRODUCER":              return 0x009A;
                case "SCI":                                      return 0x009A;
                case "CONTROL SEQUENCE INTRODUCER":              return 0x009B;
                case "CSI":                                      return 0x009B;
                case "STRING TERMINATOR":                        return 0x009C;
                case "ST":                                       return 0x009C;
                case "OPERATING SYSTEM COMMAND":                 return 0x009D;
                case "OSC":                                      return 0x009D;
                case "PRIVACY MESSAGE":                          return 0x009E;
                case "PM":                                       return 0x009E;
                case "APPLICATION PROGRAM COMMAND":              return 0x009F;
                case "APC":                                      return 0x009F;
                case "NBSP":                                     return 0x00A0;
                case "SHY":                                      return 0x00AD;
                case "LATIN CAPITAL LETTER GHA":                 return 0x01A2;
                case "LATIN SMALL LETTER GHA":                   return 0x01A3;
                case "CGJ":                                      return 0x034F;
                case "ALM":                                      return 0x061C;
                case "SYRIAC SUBLINEAR COLON SKEWED LEFT":       return 0x0709;
                case "KANNADA LETTER LLLA":                      return 0x0CDE;
                case "LAO LETTER FO FON":                        return 0x0E9D;
                case "LAO LETTER FO FAY":                        return 0x0E9F;
                case "LAO LETTER RO":                            return 0x0EA3;
                case "LAO LETTER LO":                            return 0x0EA5;
                case "TIBETAN MARK BKA- SHOG GI MGO RGYAN":      return 0x0FD0;
                case "FVS1":                                     return 0x180B;
                case "FVS2":                                     return 0x180C;
                case "FVS3":                                     return 0x180D;
                case "MVS":                                      return 0x180E;
                case "ZWSP":                                     return 0x200B;
                case "ZWNJ":                                     return 0x200C;
                case "ZWJ":                                      return 0x200D;
                case "LRM":                                      return 0x200E;
                case "RLM":                                      return 0x200F;
                case "LRE":                                      return 0x202A;
                case "RLE":                                      return 0x202B;
                case "PDF":                                      return 0x202C;
                case "LRO":                                      return 0x202D;
                case "RLO":                                      return 0x202E;
                case "NNBSP":                                    return 0x202F;
                case "MMSP":                                     return 0x205F;
                case "WJ":                                       return 0x2060;
                case "LRI":                                      return 0x2066;
                case "RLI":                                      return 0x2067;
                case "FSI":                                      return 0x2068;
                case "PDI":                                      return 0x2069;
                case "WEIERSTRASS ELLIPTIC FUNCTION":            return 0x2118;
                case "MICR ON US SYMBOL":                        return 0x2448;
                case "MICR DASH SYMBOL":                         return 0x2449;
                case "LEFTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE":
                    return 0x2B7A;
                case "RIGHTWARDS TRIANGLE-HEADED ARROW WITH DOUBLE VERTICAL STROKE":
                    return 0x2B7C;
                case "YI SYLLABLE ITERATION MARK": return 0xA015;
                case "PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRACKET":
                    return 0xFE18;
                case "VS1":                                                  return 0xFE00;
                case "VS2":                                                  return 0xFE01;
                case "VS3":                                                  return 0xFE02;
                case "VS4":                                                  return 0xFE03;
                case "VS5":                                                  return 0xFE04;
                case "VS6":                                                  return 0xFE05;
                case "VS7":                                                  return 0xFE06;
                case "VS8":                                                  return 0xFE07;
                case "VS9":                                                  return 0xFE08;
                case "VS10":                                                 return 0xFE09;
                case "VS11":                                                 return 0xFE0A;
                case "VS12":                                                 return 0xFE0B;
                case "VS13":                                                 return 0xFE0C;
                case "VS14":                                                 return 0xFE0D;
                case "VS15":                                                 return 0xFE0E;
                case "VS16":                                                 return 0xFE0F;
                case "BYTE ORDER MARK":                                      return 0xFEFF;
                case "BOM":                                                  return 0xFEFF;
                case "ZWNBSP":                                               return 0xFEFF;
                case "CUNEIFORM SIGN NU11 TENU":                             return 0x122D4;
                case "CUNEIFORM SIGN NU11 OVER NU11 BUR OVER BUR":           return 0x122D5;
                case "BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON CHROMA VASIS": return 0x1D0C5;
                case "VS17":                                                 return 0xE0100;
                case "VS18":                                                 return 0xE0101;
                case "VS19":                                                 return 0xE0102;
                case "VS20":                                                 return 0xE0103;
                case "VS21":                                                 return 0xE0104;
                case "VS22":                                                 return 0xE0105;
                case "VS23":                                                 return 0xE0106;
                case "VS24":                                                 return 0xE0107;
                case "VS25":                                                 return 0xE0108;
                case "VS26":                                                 return 0xE0109;
                case "VS27":                                                 return 0xE010A;
                case "VS28":                                                 return 0xE010B;
                case "VS29":                                                 return 0xE010C;
                case "VS30":                                                 return 0xE010D;
                case "VS31":                                                 return 0xE010E;
                case "VS32":                                                 return 0xE010F;
                case "VS33":                                                 return 0xE0110;
                case "VS34":                                                 return 0xE0111;
                case "VS35":                                                 return 0xE0112;
                case "VS36":                                                 return 0xE0113;
                case "VS37":                                                 return 0xE0114;
                case "VS38":                                                 return 0xE0115;
                case "VS39":                                                 return 0xE0116;
                case "VS40":                                                 return 0xE0117;
                case "VS41":                                                 return 0xE0118;
                case "VS42":                                                 return 0xE0119;
                case "VS43":                                                 return 0xE011A;
                case "VS44":                                                 return 0xE011B;
                case "VS45":                                                 return 0xE011C;
                case "VS46":                                                 return 0xE011D;
                case "VS47":                                                 return 0xE011E;
                case "VS48":                                                 return 0xE011F;
                case "VS49":                                                 return 0xE0120;
                case "VS50":                                                 return 0xE0121;
                case "VS51":                                                 return 0xE0122;
                case "VS52":                                                 return 0xE0123;
                case "VS53":                                                 return 0xE0124;
                case "VS54":                                                 return 0xE0125;
                case "VS55":                                                 return 0xE0126;
                case "VS56":                                                 return 0xE0127;
                case "VS57":                                                 return 0xE0128;
                case "VS58":                                                 return 0xE0129;
                case "VS59":                                                 return 0xE012A;
                case "VS60":                                                 return 0xE012B;
                case "VS61":                                                 return 0xE012C;
                case "VS62":                                                 return 0xE012D;
                case "VS63":                                                 return 0xE012E;
                case "VS64":                                                 return 0xE012F;
                case "VS65":                                                 return 0xE0130;
                case "VS66":                                                 return 0xE0131;
                case "VS67":                                                 return 0xE0132;
                case "VS68":                                                 return 0xE0133;
                case "VS69":                                                 return 0xE0134;
                case "VS70":                                                 return 0xE0135;
                case "VS71":                                                 return 0xE0136;
                case "VS72":                                                 return 0xE0137;
                case "VS73":                                                 return 0xE0138;
                case "VS74":                                                 return 0xE0139;
                case "VS75":                                                 return 0xE013A;
                case "VS76":                                                 return 0xE013B;
                case "VS77":                                                 return 0xE013C;
                case "VS78":                                                 return 0xE013D;
                case "VS79":                                                 return 0xE013E;
                case "VS80":                                                 return 0xE013F;
                case "VS81":                                                 return 0xE0140;
                case "VS82":                                                 return 0xE0141;
                case "VS83":                                                 return 0xE0142;
                case "VS84":                                                 return 0xE0143;
                case "VS85":                                                 return 0xE0144;
                case "VS86":                                                 return 0xE0145;
                case "VS87":                                                 return 0xE0146;
                case "VS88":                                                 return 0xE0147;
                case "VS89":                                                 return 0xE0148;
                case "VS90":                                                 return 0xE0149;
                case "VS91":                                                 return 0xE014A;
                case "VS92":                                                 return 0xE014B;
                case "VS93":                                                 return 0xE014C;
                case "VS94":                                                 return 0xE014D;
                case "VS95":                                                 return 0xE014E;
                case "VS96":                                                 return 0xE014F;
                case "VS97":                                                 return 0xE0150;
                case "VS98":                                                 return 0xE0151;
                case "VS99":                                                 return 0xE0152;
                case "VS100":                                                return 0xE0153;
                case "VS101":                                                return 0xE0154;
                case "VS102":                                                return 0xE0155;
                case "VS103":                                                return 0xE0156;
                case "VS104":                                                return 0xE0157;
                case "VS105":                                                return 0xE0158;
                case "VS106":                                                return 0xE0159;
                case "VS107":                                                return 0xE015A;
                case "VS108":                                                return 0xE015B;
                case "VS109":                                                return 0xE015C;
                case "VS110":                                                return 0xE015D;
                case "VS111":                                                return 0xE015E;
                case "VS112":                                                return 0xE015F;
                case "VS113":                                                return 0xE0160;
                case "VS114":                                                return 0xE0161;
                case "VS115":                                                return 0xE0162;
                case "VS116":                                                return 0xE0163;
                case "VS117":                                                return 0xE0164;
                case "VS118":                                                return 0xE0165;
                case "VS119":                                                return 0xE0166;
                case "VS120":                                                return 0xE0167;
                case "VS121":                                                return 0xE0168;
                case "VS122":                                                return 0xE0169;
                case "VS123":                                                return 0xE016A;
                case "VS124":                                                return 0xE016B;
                case "VS125":                                                return 0xE016C;
                case "VS126":                                                return 0xE016D;
                case "VS127":                                                return 0xE016E;
                case "VS128":                                                return 0xE016F;
                case "VS129":                                                return 0xE0170;
                case "VS130":                                                return 0xE0171;
                case "VS131":                                                return 0xE0172;
                case "VS132":                                                return 0xE0173;
                case "VS133":                                                return 0xE0174;
                case "VS134":                                                return 0xE0175;
                case "VS135":                                                return 0xE0176;
                case "VS136":                                                return 0xE0177;
                case "VS137":                                                return 0xE0178;
                case "VS138":                                                return 0xE0179;
                case "VS139":                                                return 0xE017A;
                case "VS140":                                                return 0xE017B;
                case "VS141":                                                return 0xE017C;
                case "VS142":                                                return 0xE017D;
                case "VS143":                                                return 0xE017E;
                case "VS144":                                                return 0xE017F;
                case "VS145":                                                return 0xE0180;
                case "VS146":                                                return 0xE0181;
                case "VS147":                                                return 0xE0182;
                case "VS148":                                                return 0xE0183;
                case "VS149":                                                return 0xE0184;
                case "VS150":                                                return 0xE0185;
                case "VS151":                                                return 0xE0186;
                case "VS152":                                                return 0xE0187;
                case "VS153":                                                return 0xE0188;
                case "VS154":                                                return 0xE0189;
                case "VS155":                                                return 0xE018A;
                case "VS156":                                                return 0xE018B;
                case "VS157":                                                return 0xE018C;
                case "VS158":                                                return 0xE018D;
                case "VS159":                                                return 0xE018E;
                case "VS160":                                                return 0xE018F;
                case "VS161":                                                return 0xE0190;
                case "VS162":                                                return 0xE0191;
                case "VS163":                                                return 0xE0192;
                case "VS164":                                                return 0xE0193;
                case "VS165":                                                return 0xE0194;
                case "VS166":                                                return 0xE0195;
                case "VS167":                                                return 0xE0196;
                case "VS168":                                                return 0xE0197;
                case "VS169":                                                return 0xE0198;
                case "VS170":                                                return 0xE0199;
                case "VS171":                                                return 0xE019A;
                case "VS172":                                                return 0xE019B;
                case "VS173":                                                return 0xE019C;
                case "VS174":                                                return 0xE019D;
                case "VS175":                                                return 0xE019E;
                case "VS176":                                                return 0xE019F;
                case "VS177":                                                return 0xE01A0;
                case "VS178":                                                return 0xE01A1;
                case "VS179":                                                return 0xE01A2;
                case "VS180":                                                return 0xE01A3;
                case "VS181":                                                return 0xE01A4;
                case "VS182":                                                return 0xE01A5;
                case "VS183":                                                return 0xE01A6;
                case "VS184":                                                return 0xE01A7;
                case "VS185":                                                return 0xE01A8;
                case "VS186":                                                return 0xE01A9;
                case "VS187":                                                return 0xE01AA;
                case "VS188":                                                return 0xE01AB;
                case "VS189":                                                return 0xE01AC;
                case "VS190":                                                return 0xE01AD;
                case "VS191":                                                return 0xE01AE;
                case "VS192":                                                return 0xE01AF;
                case "VS193":                                                return 0xE01B0;
                case "VS194":                                                return 0xE01B1;
                case "VS195":                                                return 0xE01B2;
                case "VS196":                                                return 0xE01B3;
                case "VS197":                                                return 0xE01B4;
                case "VS198":                                                return 0xE01B5;
                case "VS199":                                                return 0xE01B6;
                case "VS200":                                                return 0xE01B7;
                case "VS201":                                                return 0xE01B8;
                case "VS202":                                                return 0xE01B9;
                case "VS203":                                                return 0xE01BA;
                case "VS204":                                                return 0xE01BB;
                case "VS205":                                                return 0xE01BC;
                case "VS206":                                                return 0xE01BD;
                case "VS207":                                                return 0xE01BE;
                case "VS208":                                                return 0xE01BF;
                case "VS209":                                                return 0xE01C0;
                case "VS210":                                                return 0xE01C1;
                case "VS211":                                                return 0xE01C2;
                case "VS212":                                                return 0xE01C3;
                case "VS213":                                                return 0xE01C4;
                case "VS214":                                                return 0xE01C5;
                case "VS215":                                                return 0xE01C6;
                case "VS216":                                                return 0xE01C7;
                case "VS217":                                                return 0xE01C8;
                case "VS218":                                                return 0xE01C9;
                case "VS219":                                                return 0xE01CA;
                case "VS220":                                                return 0xE01CB;
                case "VS221":                                                return 0xE01CC;
                case "VS222":                                                return 0xE01CD;
                case "VS223":                                                return 0xE01CE;
                case "VS224":                                                return 0xE01CF;
                case "VS225":                                                return 0xE01D0;
                case "VS226":                                                return 0xE01D1;
                case "VS227":                                                return 0xE01D2;
                case "VS228":                                                return 0xE01D3;
                case "VS229":                                                return 0xE01D4;
                case "VS230":                                                return 0xE01D5;
                case "VS231":                                                return 0xE01D6;
                case "VS232":                                                return 0xE01D7;
                case "VS233":                                                return 0xE01D8;
                case "VS234":                                                return 0xE01D9;
                case "VS235":                                                return 0xE01DA;
                case "VS236":                                                return 0xE01DB;
                case "VS237":                                                return 0xE01DC;
                case "VS238":                                                return 0xE01DD;
                case "VS239":                                                return 0xE01DE;
                case "VS240":                                                return 0xE01DF;
                case "VS241":                                                return 0xE01E0;
                case "VS242":                                                return 0xE01E1;
                case "VS243":                                                return 0xE01E2;
                case "VS244":                                                return 0xE01E3;
                case "VS245":                                                return 0xE01E4;
                case "VS246":                                                return 0xE01E5;
                case "VS247":                                                return 0xE01E6;
                case "VS248":                                                return 0xE01E7;
                case "VS249":                                                return 0xE01E8;
                case "VS250":                                                return 0xE01E9;
                case "VS251":                                                return 0xE01EA;
                case "VS252":                                                return 0xE01EB;
                case "VS253":                                                return 0xE01EC;
                case "VS254":                                                return 0xE01ED;
                case "VS255":                                                return 0xE01EE;
                case "VS256":                                                return 0xE01EF;
                default:
                    throw new ArgumentException();
                }
            }

            return char.ConvertFromUtf32(getCodePoint(alias));
        }

    }
}
